### PR TITLE
Cache SEL and Class pointers

### PR DESCRIPTION
**Pull request by elnormous**
Looking up SEL and Class pointers every time they are needed is not efficient, because Objective-C runtime has to look up the cache every time. So I store pointers to classes and SELs that are used multiple times for later use.

### CODE REVIEW

**Comment by jimon** [comment]
Thanks for contribution! :+1: 
Just one comment: please either make all sel_registerName in separate lines, either don't move them to separate lines if selector is only used one, so the code will be more consistent.

**Comment by elnormous** [comment]
What do you mean by separate lines? Do you want me to move all the sel_registerName to the top of the main()?

**Comment by jimon** [comment]
I mean in some cases you moved them to separate lines like `static SEL sendEventSel = sel_registerName("sendEvent");` so they are only called once, but in some cases we also have `((void (*)(id, SEL, id))objc_msgSend)(window, sel_registerName("setTitle:"), titleString);` ... maybe just move this selectors to statics as well? Probably doesn't make much sense except for consistency. What's your opinion on this one?

**Comment by elnormous** [comment]
Ok, will do that.

**Comment by elnormous** [comment]
Please check out the last commit. I declared a Class, Protocol and SEL variable for each class, protocol and Objective-C method used. Also casting objc_msgSend to accept Class as first parameter where needed. And fixed the implicit cast from double to float by adding f to parameters of glVertex3f.

**Comment by elnormous** [comment]
Also sorry for reformatting, Xcode did that automatically.

**Comment by jimon** [comment]
Briefly checked - looks nice! :+1: Please just change it back to tab=4 spaces, thanks!

**Comment by elnormous** [comment]
Done.

**Comment by jimon** [comment]
Merged by hand to fix whitespace issues, in the future please just enable whitespace view in your editor of choice : changing whitespaces in whole file just messes up the diff and the code becomes less  traceable ...

**Pull request merged**
